### ISSUE TITLE
Proposal: Fetch MailAppSecret from KeyVault

### ISSUE THREAD

**Issue by FabienTschanz** [ykuijs/M365DSC_CICD#36]
Currently, the `variables.yaml` file contains a definition for `MailAppSecret`, where we're supposed to put the secret for the mail app registration in. Committing secrets into a source repository should be avoided, so I suggest changing this to the identifier of the secret name in the KeyVault and that's where we store our mail app secret. During runtime of `CheckDscCompliance.ps1`, we access they KeyVault, fetch the secret value with the name of the secret, and then use it for further requests. 

```yaml
# variables.yaml
- name: MailAppSecret
  type: string
  # Password secret to the email application
  # Only applicable if UseMail is set to true!
  default:
```
